-   repo: https://github.com/pre-commit/pre-commit.git
    sha: e5669ca135901120495e4d500805537abb856a1c
    hooks:
    -   id: validate_config
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e626cd57090d8df0be21e4df0f4e55cc3511d6ab
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args:
        - --no-sort-keys
        - --autofix
        - --indent
        - '4'
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=md,txt
