-   repo: https://github.com/pre-commit/pre-commit.git
    sha: bbf1f62ed686a3e321280703a227fbd957e76151
    hooks:
    -   id: validate_config
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 18d7035de5388cc7775be57f529c154bf541aab9
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args:
        - --no-sort-keys
        - --autofix
        - --indent
        - '4'
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=md,txt
